### ISSUE TITLE
网盘版本缺少run.sh

### ISSUE THREAD

**Issue by shlinym** [figozhang/runninglinuxkernel_4.0#10]
Hi, 

我下载了网盘版本，但是发现缺少了run.sh脚本。
github的repo是有run.sh

我想，这个不同会容易造成困惑(如果不仔细比较的话)。

**Comment by shlinym** [comment]
除此之外，我还遇到一些错误是网盘有，而github没有的问题，

比如_install_arm32/init.d/rcS里，网盘丢失了mkdir -p /mnt
而github上是正常的

so，建议对网盘更新一下，与github保持一直

谢谢

**Comment by figozhang** [comment]
你说的网盘是那个？ 百度网盘吗？百度网盘提供的 vmware+优麒麟Linux 18.04的镜像

**Comment by figozhang** [comment]
你可以到码云上下载，速度会比较快。
https://gitee.com/benshushu/runninglinuxkernel_4.0
