### ISSUE TITLE
[入门篇]印刷错误

### ISSUE THREAD

**Issue by shlinym** [figozhang/runninglinuxkernel_4.0#12]
109页

实验3：为虚拟设备编写驱动

代码
```
static char *device_buffer;
```
这里device_buffer是一个野指针，没有任何定义在后续的read和write就直接使用了

然后错误2是在demodrv_read函数中，
```
need_read = max_free > count ? lbuf : max_free;
```
没有找到lbuf的定义，推测是不是该为count?

**Comment by figozhang** [comment]
98 static int __init simple_char_init(void)
   99 {
  100         int ret;
  101
  102         device_buffer = kmalloc(MAX_DEVICE_BUFFER_SIZE, GFP_KERNEL);
  103         if (!device_buffer)
  104                 return -ENOMEM;

在102行里有，为这个buffer分配内存

**Comment by shlinym** [comment]
OK，我已经从码云拉取了代码，码云是上的代码时OK的，主要是因为我从github上提供的百度网盘链接下载的代码，然后上面没有实验代码，所以我的代码时参照书上的代码写的，书上有些代码是缺失的，因此导致这个问题的产生
