### ISSUE TITLE
repo address may be wrong

### ISSUE THREAD

**Issue by liyangorg** [figozhang/runninglinuxkernel_4.0#19]
`➜  tiny git clone https://github.com/figozhang/runninglinuxkernel_4.0.git
tig: Not a git repository
➜  tiny git clone git@github.com:figozhang/runninglinuxkernel_4.0.git
tig: Not a git repository
➜  tiny
`

**Comment by figozhang** [comment]
可以访问国内的git repo：
https://dev.tencent.com/u/benshushu/p/runninglinuxkernel_4.0
