### ISSUE TITLE
[ feature request] modules related dir for basic rootfs

### ISSUE THREAD

**Issue by miraclemore** [figozhang/runninglinuxkernel_4.0#4]
Due to we need to study linux kernel by linux kernel modules.
So I regard that we should add lib/modules/$(version) in the rootfs for newbee.
if not, it will cause rmmod failed!
And also there is no shared mount point for module install. maybe we can used virt-9p for that.

**Comment by figozhang** [comment]
yes, welcome your patch

**Comment by miraclemore** [comment]
I already create a pull request for that .
Here is the [patch](https://github.com/figozhang/runninglinuxkernel_4.0/pull/5)
if any problems, please let me know

**Comment by miraclemore** [comment]
create a new pull request for that!
Here is the 2nd version [patch](https://github.com/figozhang/runninglinuxkernel_4.0/pull/6)

**Comment by miraclemore** [comment]
As u commented on the 2nd patch. I already merge the arm related task.
Here is the 3rd version [patch](https://github.com/figozhang/runninglinuxkernel_4.0/pull/7)
